FIND_PATH(SQRAT_INCLUDE_DIR sqrat.h 
    PATHS ${SQRAT_ROOT}
        ENV SQRAT_ROOT 
    PATH_SUFFIXES include)

IF(SQRAT_INCLUDE_DIR)
   SET(SQRAT_FOUND TRUE)
ENDIF(SQRAT_INCLUDE_DIR)

IF(SQRAT_FOUND)
   IF (NOT SQRAT_FIND_QUIETLY)
	   MESSAGE(STATUS "Found Sqrat: ${SQRAT_INCLUDE_DIR}")
   ENDIF(NOT SQRAT_FIND_QUIETLY)
ELSE(SQRAT_FOUND)
   IF (SQRAT_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Sqrat")
   ENDIF(SQRAT_FIND_REQUIRED)
ENDIF(SQRAT_FOUND)

